### PR TITLE
Sort biome map; Edit keymap; mess with sizes.

### PR DESCRIPTION
**Pull request by joeheyming**
Hey, I really like the repo.
I wanted to help make a contribution.

I was messing around with the size of the map and
was having trouble getting to centre.

It was drawing funny when I doubled the map size.
I tracked it down to
mc-biome-viewer-center-camera was not working
because it had a hard-coded 16, which I think
should be mc-biome-viewer-row-chunks-in-camera.

I tested it a few times and think it works.

I also was looking at the char map and noticed
it was not sorted, so I did M-x sort-lines on it.

I was trying to navigate using the pnfb keys and felt
that using up/down/left/right was more natural.

I updated the key map to use Ctrl up/down/left/right.

I hope this isn't too invasive :-/

I also noticed there were issues rendering certain
biomes was not exactly mono-space.  I get wonky sized
maps when I navigate around because of this.

### CODE REVIEW

**Comment by joeheyming** [comment]
Screen Shot 2020-03-30 at 8 58 29 PM
 Here is an example of a not entirely square map :-/

**Comment by joeheyming** [comment]
Stone beach might be the problem? ✧
Same with sunflower plains: ⁂ 

I'm not sure if they are good monospace fonts

**Comment by LaurenceWarne** [comment]
Hi, thanks for the contribution, I'm glad you like the project.

This all looks fine except I think there may be a misunderstanding with ```mc-biome-viewer-centre-camera```. What should happen is that you input the x and z coordinate and the camera will translate itself so that (x, z) is the centre coordinate of the camera, like so (here with x=1000, z=-2000):

mc-biome-viewer-centre-ex

So the /16 corresponds to the conversion from chunk coordinates to world coordinates (one character is hard coded as one chunk, I probably should have made this clear somewhere).

I tried out your changes a few times, and I can't tell what you want :) , but if you give me an example I'd be happy to add it as a different command. Of course If you think I've overlooked something in the original function, let me know.

I thought I got all of the dodgy characters, thanks for finding this, I'll probably set them to some ascii characters so they're more in keeping with the others.

**Comment by joeheyming** [comment]
Hey I reverted the size change and instead introduced a variable for the chunk size.  I see what you mean.  The change was a bad one, but I still hope what I have is useful.

**Comment by LaurenceWarne** [comment]
Of course! Thanks again.

**Pull request merged**
